[build]
publish = "public"
command = "hugo --gc --minify -b ${DEPLOY_PRIME_URL}"

[build.environment]
HUGO_VERSION = "0.138.0"

[[redirects]]
  from = "/admin/*"
  to = "/admin/index.html"
  status = 200

# Add this for GitHub OAuth
[[redirects]]
  from = "/auth"
  to = "/.netlify/functions/auth"
  status = 200
